# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataaccess', '0003_auto_20160522_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('count', models.IntegerField()),
                ('discont', models.FloatField()),
                ('image', models.CharField(max_length=50)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataaccess.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.CharField(max_length=50),
        ),
    ]
