# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataaccess', '0005_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
