# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataaccess', '0006_product_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discont',
            new_name='discount',
        ),
    ]
