# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataaccess', '0010_auto_20160524_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('productid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataaccess.Product')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataaccess.UserProfile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set([('username', 'productid')]),
        ),
    ]
