# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataaccess', '0011_auto_20160524_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('delivstatus', models.BooleanField()),
                ('orderid', models.CharField(max_length=30)),
                ('duedate', models.CharField(max_length=30)),
                ('contactno', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('paymentmethod', models.CharField(max_length=30)),
                ('paymentinfo', models.CharField(max_length=30)),
                ('productid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataaccess.Product')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataaccess.UserProfile')),
            ],
        ),
    ]
