# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataaccess', '0012_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivstatus',
            field=models.CharField(max_length=10),
        ),
    ]
